### ISSUE TITLE
There is now a dockerized version available

### ISSUE THREAD

**Issue by jcfr** [xoofx/git-rocket-filter#4]
@xoofx  Thanks for creating this nice project, Very useful.

To facilitate its usage without having to install all the requirements, few days ago I created a docker container for an easier installation and use.

See https://github.com/jcfr/dockgit-rocket-filter

**Comment by xoofx** [comment]
Thanks for this, could be useful indeed

**Comment by xoofx** [comment]
git-rocket-filter can be installed as a .NET global tool now:

```
dotnet tool install -g git-rocket-filter
```

**Comment by jcfr** [comment]
Thanks for the update.

Out of curiosity, does this approach allow the use of `git-rocket-filter` across platform ? If not, this was what the dockerized version allow to do. It allows to make use of your outstanding work without having to install dotnet. The only requirement being docker.

**Comment by xoofx** [comment]
yeah, it doesn't replace a dockerized version, just that it makes the whole update lifecycle/distribution a lot more easier

**Comment by jcfr** [comment]
What do you think if I add one line of text [here](https://github.com/xoofx/git-rocket-filter#download) in the README section to reference the dockerized version ?

**Comment by xoofx** [comment]
Yep PR welcome, just specify that the docker version might not point to the latest

**Comment by jcfr** [comment]
See https://github.com/xoofx/git-rocket-filter/pull/9
