### ISSUE TITLE
Add an option to preserve merge commits

### ISSUE THREAD

**Issue by HellBrick** [xoofx/git-rocket-filter#6]
I have a repo where we rebase feature branches on master and then merge them into it **without fast-forwarding** once they are finished. This makes the commit log look [like this](https://i.imgur.com/EKcvP1y.png).

When trying to remove all the traces of a specific directory from the repo via GitRocketFilter, I've discovered that it unconditionally removes merge commits if it considers them empty. Here's the culprit: https://github.com/xoofx/GitRocketFilter/blob/ad205815153ed0538e3afe04f2c5e6473f4f3812/src/RocketFilterApp.cs#L354-L360

I see the logic behind this, but in this particular case it produces a lot of false positives and removes the commits I'd like to preserve. So I'd like to suggest adding a new `--preserve-merge-commits` option that, if enabled, would add an additional check for the parent count and only allow dropping an empty commit if it has less than two parents. I hacked together a hardcoded version of it in https://github.com/HellBrick/GitRocketFilter/commit/74356a2082fb8d4c10f97ded1569ac5661cfdf5c and it seems to be doing what it's supposed to without screwing up anything unrelated, so I could add a proper option for it and send a PR if you agree this is a useful feature to have.

**Comment by xoofx** [comment]
sure that option can help, PR welcome.
